# Generated by Django 3.0.7 on 2020-07-06 20:05

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assunto', '0001_initial'),
        ('banca', '0001_initial'),
        ('instituicao', '0001_initial'),
        ('cargo', '0001_initial'),
        ('disciplina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta_questao', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Questao')),
                ('letra_a', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Alternativa A')),
                ('letra_b', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Alternativa B')),
                ('letra_c', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Alternativa C')),
                ('letra_d', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Alternativa D')),
                ('letra_e', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Alternativa E')),
                ('assunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assunto.Assunto')),
                ('banca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banca.Banca')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo.Cargo')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disciplina.Disciplina')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituicao.Instituicao')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_comentario', models.DateTimeField(default=django.utils.timezone.now)),
                ('comentario', models.TextField()),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='questao.Questao')),
            ],
        ),
    ]
